# ブログのタイトル
title: "チリツモ旅 -チリも積もれば旅となる-"

# ブログの説明文（メタタグやテーマによってトップページ等に表示されます）
description: "関西在住のぽぽとももの夫婦が財テクを駆使して、旅を楽しむブログです"

# 使用するデザインテーマ
remote_theme: mmistakes/minimal-mistakes

# スキンの選択（カラーテーマ）
# 選択肢: "default", "air", "aqua", "contrast", "dark", "neon", "mint", "sunrise" など
minimal_mistakes_skin: "dark"

# 言語設定（日付の表示などを日本語にするため）
locale: "ja-JP"

# サイドバーに表示するプロフィール設定
author:
  name   : "ぽぽ"
  bio    : "関西在住のサラリーマン。<br>夫婦二人の旅の記録と節約と財テクで貯めたポイントの活用方法について発信しています。"
  # avatar : "/assets/images/biophoto.jpg" # 顔写真やアイコン画像を使う場合
  links:
    - label: "HOME"
      icon: "fas fa-house"
      url: "/popomomoblog/"
    - label: "ステータス"
      icon: "fas fa-shield-alt"
      url: "/popomomoblog/status/"
    - label: "ワールドマップ"
      icon: "fas fa-compass"
      url: "/popomomoblog/map/"
    - label: "クエストボード<br>（バケットリスト）"
      icon: "fas fa-clipboard-list"
      url: "/popomomoblog/bucket-list/"
    - label: "セーブポイント<br>(クエストとポイント推移)"
      icon: "fas fa-church"
      url: "/popomomoblog/adventure-log/"
    - label: "ぼうけんの書庫<br>(カテゴリー一覧)"
      icon: "fas fa-fw fa-folder-open"
      url: "/popomomoblog/categories/"
    - label: "タグ一覧"
      icon: "fas fa-fw fa-tag"
      url: "/popomomoblog/tags/"          
    - label: "サイト内検索"
      icon: "fas fa-fw fa-search"
      url: "/popomomoblog/search/"

# 利用プラグイン
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# あなたのブログのURL（[ユーザー名]の部分をご自身のGitHubアカウント名に変更してください）
url: "https://popomomo-ux.github.io"

# サブディレクトリを使わずにルート直下で公開する場合は空欄のままでOKです
baseurl: "/popomomoblog"

# ページや記事全体のデフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

# 検索機能の設定
search: false
search_provider: "lunr"

# 作成ページを読み込ませる
include:
  - "_pages"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-1PQ3C1HWM3"
    
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: false
